import Head from "next/head";

import { Divider } from "antd";

import Products from "../components/Products";
import Layout from "../components/Layout";
import HeaderCarousel from "../components/HeaderCarousel";
import Navbar from "../components/Navbar";

import { API_URL } from "../utils/urls";

export default function Home({ products }) {
  return (
    <>
      <Head>
        <title>E-commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.svg" />
      </Head>
      <Navbar />
      <HeaderCarousel />
      <Divider />
      <Layout>
        <Products products={products} maxArray={8} />
      </Layout>
    </>
  );
}

export async function getStaticProps() {
  const query = "?populate=*";
  const products_res = await fetch(API_URL + "products/" + query);
  const products = await products_res.json();
  return { props: { products } };
}
